import = ["~/.config/alacritty/catppuccin-mocha.toml"]
# import = ["~/.config/alacritty/catppuccin-latte.toml"]
# import = ["~/.config/alacritty/dracula.toml"]
# import = ["~/.config/alacritty/one-dark.toml"]

[env]
WINIT_X11_SCALE_FACTOR = "1"
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 12

[font.bold]
family = "FantasqueSansM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FantasqueSansM Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FantasqueSansM Nerd Font"
style = "Italic"

[font.normal]
family = "FantasqueSansM Nerd Font"

[font.offset]
x = 0
y = 2

[window]
opacity = 1
